# Generated by Django 3.0 on 2022-12-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartas',
        ),
        migrations.DeleteModel(
            name='Observaciones',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
